### PR TITLE
[Testing] Testing PR for #28.

### PR DESCRIPTION
**Pull request by ashfurrow**
See #34.

### CODE REVIEW

**Comment by freak4pc** [comment]
A bit nitpicky , but do we need the `peril-` prefix on the bot's name? since it appears in the bottom test sheet as well, can't it just be named RxSwiftCommunityBot or something around that? or is that a pre-set prefix for that GitHub app ?

**Comment by orta** [comment]
The bot name should be the name of the GH App, so I think you can rename that - there's a global namespace, but it should be ifne

**Comment by orta** [comment]
Looks like GH will lowercase the app name entirely, then add `[bot]` next to it

**Comment by ashfurrow** [comment]
Okay cool, I'll rename the bot.

**Comment by ashfurrow** [comment]
Oh! Someone already did :)

**Comment by ashfurrow** [comment]
Okay looks like this worked (as in, this repo doesn't have a changelog, so nothing was commented by Peril). I'm going to add the Action repo and make a follow-up test PR there.

**Pull request closed without merging**
