### PR TITLE
First draft of contributor guidelines

### LINKED ISSUE #1: Initial Guidelines
@orta and I had a lot of fun writing up [Moya's contributor guidelines](https://github.com/Moya/contributors), and I think we need something similar for this org. 

Necessary things, I think:
- Code of conduct
- Expectations of contributors (Moya's is basically "don't stress about this")
- How to consider moving a repo to the org (probably open an issue on this repo to discuss?)
- ???

I feel strongly that we should have a "contributors" team and, once anyone sends a PR that gets merged, they should be added to that team and have push access. We can use GitHub to protect master branches against force-pushing to mitigate potential problems, but this really helps people feel a sense of ownership of the project and encourages them to contribute more.

### PR DESCRIPTION
**Pull request by ashfurrow**
A few things worthy of discussing:
- We're referencing Moya's contributor guidelines instead of repeating them.
- We also point out the things unique to RxSwiftCommunity.
- Code of Conduct includes only my email address – I'm happy to accept that responsibility, but if someone would like to add theirs, that's :ok_hand: with me.

Of course, these guidelines can evolve as we gain more experience, but I think this is a solid place to start.

Fixes #1.

### CODE REVIEW

**Comment by orta** [comment]
Yep, this is the direction that feels good to me.

**Comment by esttorhe** [comment]
:ok_hand: :100:

**Comment by ashfurrow** [comment]
Sounds like this is good to go – @esttorhe would you like to do the honours?

**Comment by esttorhe** [comment]
👌🏼

**Pull request merged**
